# Generated by Django 4.1.3 on 2023-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mentor', 'Ментор'), ('student', 'Cтудент')], default='student', max_length=255, verbose_name='Роль'),
        ),
    ]
